module.exports = {
  important: true,
  content: ["./index.html", "./src/**/*.{js,jsx,ts,tsx}"],
  safelist: [
    "rounded-l-md",
    "rounded-r-md",
    "w-full",
    "bg-@main-background",
    "border",
    "border-@MainGreen",
    "border-@tag-text-3",
    "pl-2",
    "pr-1",
  ],
  theme: {
    extend: {
      colors: {
        "@icondark": "#626F86",
        "@lightmaingreen": "#C8EBEB",
        "@MainGreen": "#13C2C2",
        "@light2green": "#E6FFFB",
        "@hovergreen": "#5CDBD3",
        "@textheading": "rgba(0, 0, 0, 0.88)",
        "@textlable": "rgba(0, 0, 0, 0.65)",
        "@placeholder": "rgba(0, 0, 0, 0.25)",
        "@textdisable": "rgba(0, 0, 0, 0.25)",
        "@textdiscription": "rgba(0, 0, 0, 0.45)",
        "@hover&disable": "rgba(0, 0, 0, 0.04)",
        "@border1": "rgba(0, 0, 0, 0.15)",
        "@border2": "rgba(0, 0, 0, 0.06)",
        "@lightbggrey": "rgba(0, 0, 0, 0.02)",
        "@main-background": "#F7F8FA",
        "@tag-text-1": "#FF7A45",
        "@tag-bg-1": "#FFF2E8",
        "@tag-text-2": "#52C41A",
        "@tag-bg-2": "#F6FFED",
        "@tag-text-3": "#1677FF",
        "@tag-bg-3": "#E6F4FF",
        "@blue/2": "#BAE0FF",
        "@orange-start": "#FFA826",
        "@orange-end": "#FF7875",
        "@gray-bg": "#EBEBEB",
        "@pink-bg": "#FFE3DB",
        "@red-text": "#FF5353",
        "@light-green-1": "#D9F5CA",
        "@red-6": "#F5222D",
        "@sider-bg": "rgb(230,255,251)",
      },
    },
  },
  plugins: [],
  corePlugins: {
    preflight: false,
  },
};
